### ISSUE TITLE
Finufft Matlab Installation on Mac OS 15

### ISSUE THREAD

**Issue by nalhassanieh** [flatironinstitute/finufft#752]
I am having an issue installing Finufft for Matlab R2025b. Attached are the make.inc file I used along with the error message. 

[terminalOutput.txt](https://github.com/user-attachments/files/23661959/terminalOutput.txt)
[make.inc.txt](https://github.com/user-attachments/files/23662076/make.inc.txt)

Thank you.

**Comment by DiamonDinoia** [comment]
Hi, can you try cmake instead? 

```bash
git clone https://github.com/flatironinstitute/finufft.git
cd finufft
cmake -S . -B build -DFINUFFT_BUILD_TESTS=ON -DDFINUFFT_BUILD_MATLAB=ON
cmake --build build
ctest --test-dir build
cmake --install build

```

**Comment by nalhassanieh** [comment]
We tried cmake, as you proposed and with other variations, but the error persists. Here is the output:

Undefined symbols for architecture arm64:
  "_mexCreateMexFunction", referenced from:
      <initial-undefines>
  "_mexDestroyMexFunction", referenced from:
      <initial-undefines>
  "_mexFunctionAdapter", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [matlab/finufft.mexmaca64] Error 1
make[1]: *** [matlab/CMakeFiles/finufft_mex.dir/all] Error 2
make: *** [all] Error 2

**Comment by DiamonDinoia** [comment]
I'm not the Matlab expert so I wait for the others to give more accurate advice. The only thing I can think of is do you have the parallel toolbox installed?

**Comment by lu1and10** [comment]
Update, temporarily fixed by @danfortunato that apple native clang + brew libomp is breaking with matlab 2025b.  Switching to use gnu gcc works for now.

**Comment by h-shaw** [comment]
I am having the same issue, even when I use gcc I still get symbol(s) not found for architecture arm64 even when using matlab 2025a

**Comment by danfortunato** [comment]
@h-shaw Can you post the terminal output?

**Comment by h-shaw** [comment]
[outputcmake.txt](https://github.com/user-attachments/files/23783109/outputcmake.txt)

**Comment by h-shaw** [comment]
[make.inc.txt](https://github.com/user-attachments/files/23783200/make.inc.txt)

[gnumatlab.txt](https://github.com/user-attachments/files/23783205/gnumatlab.txt)

here's the make inc and output when using gnu gcc from make.inc.macosx_gcc-14

**Comment by lu1and10** [comment]
> [make.inc.txt](https://github.com/user-attachments/files/23783200/make.inc.txt)
> 
> [gnumatlab.txt](https://github.com/user-attachments/files/23783205/gnumatlab.txt)
> 
> here's the make inc and output when using gnu gcc from make.inc.macosx_gcc-14
> 

For makefile Mex build, you may need follow @danfortunato https://github.com/danfortunato/matlab-gcc to change matlab Mex to use gnu gcc too, so both libfinufft and mex file are both built with gnu gcc.


For the cmake Mex build, it might be something related to the what @danfortunato finds about issue in Apple linker.

**Comment by danfortunato** [comment]
Can you add `-v` to `MFLAGS` in your make.inc and send the output again?

**Comment by h-shaw** [comment]
[make.inc.txt](https://github.com/user-attachments/files/23786794/make.inc.txt)

[outputtxt.txt](https://github.com/user-attachments/files/23786810/outputtxt.txt)
here are the new make and output files, I tried  placing the gcc in the matlab mexopt folder but that didn't help. I am using GNU make 3.81 thanks

**Comment by lu1and10** [comment]
With gnu gcc, if you add -ld_classic to MFLAGS, does it help?

**Comment by h-shaw** [comment]
Yes! -ld_classic solved the issues, thank you so much everyone

**Comment by lu1and10** [comment]
Thanks for testing, I added the -ld_classic to one of the Mac make.inc files
https://github.com/flatironinstitute/finufft/commit/20393637d22759010f5352857250f035cb72a5f4
It seems to be a new issue, before we only need the -ld_classic or -ld64 for building libfinufft binary.
Now with the new Xcode and newer version Matlab, compiling the mex interface seems to need the flag too.

**Comment by danfortunato** [comment]
@lu1and10 Maybe it’s best to pass $LDFLAGS directly to $MFLAGS in make.inc?

**Comment by lu1and10** [comment]
@danfortunato good question. I checked the make.inc files, all seems try to keep libfinufft linking flags independent of MFLAGS for Mex interface. I'm not sure it's intended that mex binary should not inherent the link flags from libfinufft or should change to inherent all the linking flags.

**Comment by danfortunato** [comment]
@lu1and10 I think if the static/dynamic libraries need any specific LDFLAGS to build then Mex will also need the same LDFLAGS, since a Mex build is basically the same as a dynamic library.

**Comment by bobbielf2** [comment]
I spent sometime trying to compile on my arm64 Mac, finally made it work in both Matlab_R2024a and R2025b.

Here is what I have found:
1. The Undefined symbols "___kmpc_dispatch_deinit" issue can be fixed by including BOTH homebrew and Matlab's own OpenMP.
2. The Undefined symbols "_mexCreateMexFunction" etc issue can be fixed by modifying Matlab's MEX XML file.

Here is my `make.inc` script, which combines ideas from @lu1and10 and @ahbarnett . Comments on how to modify the XML file at the end.

```
# Makefile variable overrides for cross-compiling for ARM silicon via
# clang + MATLAB on Mac OSX.
#
# This is a combination of the following
# Barnett 10/3/20: make.inc.macosx_clang_matlab
# Libin Lu 12/21/23: make.inc.macosx_arm64
# Bobbie Wu 1/3/26: Added comments about MEX XML; MATLAB+OMP fix for MATLAB_R2024+ 

# compile flags for use with clang: (note absence of -march, etc)
CFLAGS = -O3 -arch arm64

# If you're getting warning messages of the form:
#    ld: warning: object file (lib-static/libfinufft.a(finufft1d.o)) was built for
#    newer OSX version (10.13) than being linked (10.9)
# Then you can uncomment the following two lines with the older version number
# (in this example -mmacosx-version-min=10.9)
#
#CFLAGS += "-mmacosx-version-min=<OLDER OSX VERSION NUMBER>"

CXX=clang++
CC=clang

# assuming libomp and fftw are installed through homebrew
OMP_ROOT = $(shell brew --prefix libomp)
FFTW_ROOT = $(shell brew --prefix fftw)

# taken from makefile...
CFLAGS   += -I include -I/usr/local/include -I$(OMP_ROOT)/include -I$(FFTW_ROOT)/include
FFLAGS   = $(CFLAGS)
CXXFLAGS = $(CFLAGS)
LIBS += -L/usr/local/lib -L$(OMP_ROOT)/lib -L$(FFTW_ROOT)/lib
LDFLAGS += -arch arm64 -L$(OMP_ROOT)/lib -L$(FFTW_ROOT)/lib

# OpenMP with clang needs following...
OMPFLAGS = -Xpreprocessor -fopenmp
OMPLIBS = -lomp
# Also use MATLAB's shipped OpenMP (not gomp otherwise segfaults), with clang...
MOMPFLAGS = -D_OPENMP
OMPLIBS += $(shell ls -d /Applications/MATLAB_R* | sort | tail -1)/toolbox/eml/externalDependency/omp/maca64/lib/libomp.dylib
# Also use -Wl,-rpath to add MATLAB's omp lib directory to the runtime library search path
LDFLAGS += -Wl,-rpath,$(shell ls -d /Applications/MATLAB_R* | sort | tail -1)/toolbox/eml/externalDependency/omp/maca64/lib/
# since fftw3_omp doesn't work in OSX, we need...
FFTWOMPSUFFIX=threads

# MATLAB interface:
# Some of these will depend on your FFTW library location...
MFLAGS += -I/usr/local/include -I/opt/homebrew/include -L/usr/local/lib -L/opt/homebrew/lib
# may need to edit for your MATLAB version location...
MEX = $(shell ls -d /Applications/MATLAB_R* | sort | tail -1)/bin/mex

# Also see docs/install.rst for possible edits to MATLAB's MEX XML file.

# Comments about MEX XML: "make matlab" may return with the following error message:
# 
#		Undefined symbols for architecture arm64:
#		  "_mexCreateMexFunction", referenced from:
#		      <initial-undefines>
#		  "_mexDestroyMexFunction", referenced from:
#		      <initial-undefines>
#		  "_mexFunction", referenced from:
#		      <initial-undefines>
#		  "_mexFunctionAdapter", referenced from:
#		      <initial-undefines>
#		ld: symbol(s) not found for architecture arm64
#		clang++: error: linker command failed with exit code 1
# 	
# This is because the C++ MEX API by default links to certain symbols (such as
# "_mexCreateMexFunction"). But matlab/finufft.cpp is coded with the C MEX API 
# (i.e., #include "mex.h" instead of "mex.hpp").
# 
# The solution is to modify the MEX XML file to ignore the C++ MEX symbols: 
# 
#	1. Open the "mex_C++_maca64.xml" file, located in e.g.:
#
#		"~/Library/Application Support/MathWorks/MATLAB/R2025b/mex_C++_maca64.xml"
#
#   2. Identify the variable LINKEXPORTCPP, which reads:
# 	
#   	LINKEXPORTCPP="-Wl,-U,_mexCreateMexFunction -Wl,-U,_mexDestroyMexFunction ..."
# 	  
#      Redefine it as an empty string:
#
#   	LINKEXPORTCPP=""
# 
# Then "make matlab" should work without error.
```

**Comment by ahbarnett** [comment]
we believe the fix is to add ``ld_classic`` to ``make_platforms/make.inc.macosx_clang`` or this ``_matlab``

Also to apply this to cmake for the matlab build.

To do.

**Comment by ahbarnett** [comment]
fixed by 598e5a09

**Comment by ahbarnett** [comment]
and 9bc4e0a9
